### ISSUE TITLE
Works with styled-jsx?

### ISSUE THREAD

**Issue by weotch** [alin23/next-coffeescript#2]
Have you tried getting this to work with [styled-jsx](https://github.com/zeit/styled-jsx)?

With:

```coffee
import React from 'react'

export default class HomePage extends React.Component
	render: ->
		<div>
			<p>Welcome to next.js</p>
			<style jsx>
				p {
					font-weight: 'bold';
				}
			</style>
		</div>
```

I'm getting:

> Module build failed: SyntaxError: Expected one child under JSX Style tag, but got 2 (eg: <style jsx>{`hi`}</style>)

**Comment by alin23** [comment]
It works, you just have to leave a hint for Coffeescript so that the transpiler knows that the css should be compiled as a template string.

```coffeescript
import React from 'react'

export default class HomePage extends React.Component
    render: ->
        <div>
            <p>Welcome to next.js</p>
            <style jsx>{"#{}
                p {
                    font-weight: bold;
                }
            "}</style>
        </div>
```

Coffeescript knows that a string is a template string if it has one or more interpolations inside (`#{}`).
By placing a `#{}` at the beginning of the string you force Coffeescript to output what's inside `<style jsx>` as a template string, which is exactly what `styled-jsx` expects.

**Comment by weotch** [comment]
Thanks!
